language: java

services:
  - docker

sudo: required
git:
  depth: 3

before_install:
  - APP_VERSION=$([ -n "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG#*v}" || echo "${TRAVIS_BRANCH##*/}")
  - DOCEKR_IMAGE_VERSION=$([ -n "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG}" || echo "${TRAVIS_BRANCH##*/}")

script:
  - mvn package

after_success:
  - export IMAGE_TAG=java-backend;
  - export REPO=grouporga/java-backend;
  - echo "${IMAGE_TAG} ${REPO} ${DOCEKR_IMAGE_VERSION}"
  - if [ -n "${TRAVIS_TAG}" -o "${TRAVIS_BRANCH}" == "master" ]; then
    docker build -t ${IMAGE_TAG} . &&
    echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin &&
    docker tag ${IMAGE_TAG} ${REPO}:${DOCEKR_IMAGE_VERSION} &&
    docker push ${REPO};
    fi
# TODO Codacy coverage reporter does not yet support Java 9. See https://github.com/codacy/codacy-coverage-reporter/issues/76
#      ./gradlew sendCoverageToCodacy;